export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS';
export const ADD_SUBSCRIPTION_ERROR = 'ADD_SUBSCRIPTION_ERROR';
export const ADD_SUBSCRIPTION_START = 'ADD_SUBSCRIPTION_START';

export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_ERROR = 'FETCH_SUBSCRIPTIONS_ERROR';
export const FETCH_SUBSCRIPTIONS_START = 'FETCH_SUBSCRIPTIONS_START';

export const REMOVE_SUBSCRIPTION_SUCCESS = 'REMOVE_SUBSCRIPTION_SUCCESS';
export const REMOVE_SUBSCRIPTION_ERROR = 'REMOVE_SUBSCRIPTION_ERROR';
export const REMOVE_SUBSCRIPTION_START = 'REMOVE_SUBSCRIPTION_START';

export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTIONS_SUCCESS';
export const UPDATE_SUBSCRIPTION_ERROR = 'UPDATE_SUBSCRIPTIONS_ERROR';
export const UPDATE_SUBSCRIPTION_START = 'UPDATE_SUBSCRIPTIONS_START';

export const UPDATE_EDITED_SUBSCRIPTION_FORM_VALUE = 'UPDATE_EDITED_SUBSCRIPTION_FORM_VALUE';

export const SET_EDITED_SUBSCRIPTION = 'SET_EDITED_SUBSCRIPTION';
export const SET_FRESH_EDITED_SUBSCRIPTION = 'SET_FRESH_EDITED_SUBSCRIPTION';

export const TOGGLE_EDITION_MODAL = 'TOGGLE_EDITION_MODAL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
