export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION';

export const UPDATE_EDITED_SUBSCRIPTION_FORM_VALUE = 'UPDATE_EDITED_SUBSCRIPTION_FORM_VALUE';
export const SET_EDITED_SUBSCRIPTION = 'SET_EDITED_SUBSCRIPTION';
export const TOGGLE_EDITION_MODAL = 'TOGGLE_EDITION_MODAL';
export const SET_FRESH_EDITED_SUBSCRIPTION = 'SET_FRESH_EDITED_SUBSCRIPTION';
